//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UW.ClassroomPresenter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UW.ClassroomPresenter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Classroom Presenter.
        /// </summary>
        internal static string AboutClassroomPresenter {
            get {
                return ResourceManager.GetString("AboutClassroomPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Student Submissions.
        /// </summary>
        internal static string AcceptStudentSubmissions {
            get {
                return ResourceManager.GetString("AcceptStudentSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter Type:.
        /// </summary>
        internal static string AdapterType {
            get {
                return ResourceManager.GetString("AdapterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move/Resize Images..
        /// </summary>
        internal static string AddEditImages {
            get {
                return ResourceManager.GetString("AddEditImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Text..
        /// </summary>
        internal static string AddEditText {
            get {
                return ResourceManager.GetString("AddEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Connection Options.
        /// </summary>
        internal static string AdvancedConnectionOptions {
            get {
                return ResourceManager.GetString("AdvancedConnectionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Scroll.
        /// </summary>
        internal static string AutoScroll {
            get {
                return ResourceManager.GetString("AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Presentations.
        /// </summary>
        internal static string AvailablePresentations {
            get {
                return ResourceManager.GetString("AvailablePresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Template Properties.
        /// </summary>
        internal static string BackgroundPropertiesFormTitle {
            get {
                return ResourceManager.GetString("BackgroundPropertiesFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the previous slide..
        /// </summary>
        internal static string BackwardTooltipPreviousSlide {
            get {
                return ResourceManager.GetString("BackwardTooltipPreviousSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose background template.
        /// </summary>
        internal static string BkgChooseTemplate {
            get {
                return ResourceManager.GetString("BkgChooseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black text..
        /// </summary>
        internal static string BlackText {
            get {
                return ResourceManager.GetString("BlackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue text..
        /// </summary>
        internal static string BlueText {
            get {
                return ResourceManager.GetString("BlueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcasted Presentations.
        /// </summary>
        internal static string BroadcastedPresentations {
            get {
                return ResourceManager.GetString("BroadcastedPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast IP.
        /// </summary>
        internal static string BroadcastIP {
            get {
                return ResourceManager.GetString("BroadcastIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast IP Address.
        /// </summary>
        internal static string BroadcastIPAddress {
            get {
                return ResourceManager.GetString("BroadcastIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera:.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        internal static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Pictures.
        /// </summary>
        internal static string CaptureWindow {
            get {
                return ResourceManager.GetString("CaptureWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classmate.
        /// </summary>
        internal static string Classmate {
            get {
                return ResourceManager.GetString("Classmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom.
        /// </summary>
        internal static string Classroom {
            get {
                return ResourceManager.GetString("Classroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client(s).
        /// </summary>
        internal static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Command:.
        /// </summary>
        internal static string CloneCommand {
            get {
                return ResourceManager.GetString("CloneCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Deck....
        /// </summary>
        internal static string CloseDeck {
            get {
                return ResourceManager.GetString("CloseDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility.
        /// </summary>
        internal static string Compatibility {
            get {
                return ResourceManager.GetString("Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Restore Defaults.
        /// </summary>
        internal static string ConfirmRestoreDefaults {
            get {
                return ResourceManager.GetString("ConfirmRestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all properties to their default values?
        ///
        ///Changes will take effect immediately..
        /// </summary>
        internal static string ConfirmRestoreDialog {
            get {
                return ResourceManager.GetString("ConfirmRestoreDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to TCP Server....
        /// </summary>
        internal static string ConnectToTCPServer {
            get {
                return ResourceManager.GetString("ConnectToTCPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Slide to Public Deck.
        /// </summary>
        internal static string CopyToPublic {
            get {
                return ResourceManager.GetString("CopyToPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Blank &amp;Whiteboard Deck.
        /// </summary>
        internal static string CreateBlankWhiteboardDeck {
            get {
                return ResourceManager.GetString("CreateBlankWhiteboardDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom color text..
        /// </summary>
        internal static string CustomColorText {
            get {
                return ResourceManager.GetString("CustomColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Commands.
        /// </summary>
        internal static string CustomCommands {
            get {
                return ResourceManager.GetString("CustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CXP Capability Connected.
        /// </summary>
        internal static string CXPCapabilityConnected {
            get {
                return ResourceManager.GetString("CXPCapabilityConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Deck Matcher.
        /// </summary>
        internal static string DeckMatcher {
            get {
                return ResourceManager.GetString("DeckMatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decks.
        /// </summary>
        internal static string Decks {
            get {
                return ResourceManager.GetString("Decks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighter Width.
        /// </summary>
        internal static string DefaultHLWidth {
            get {
                return ResourceManager.GetString("DefaultHLWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Width.
        /// </summary>
        internal static string DefaultPenWidth {
            get {
                return ResourceManager.GetString("DefaultPenWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Settings.
        /// </summary>
        internal static string DefaultSettings {
            get {
                return ResourceManager.GetString("DefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Slide.
        /// </summary>
        internal static string DeleteSlide {
            get {
                return ResourceManager.GetString("DeleteSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Instructor Advertisement &amp;Broadcast.
        /// </summary>
        internal static string DisableAdvertisementBroadcast {
            get {
                return ResourceManager.GetString("DisableAdvertisementBroadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable free navigation, link to the instructor&apos;s current slide..
        /// </summary>
        internal static string DisableNavigationIndInstructor {
            get {
                return ResourceManager.GetString("DisableNavigationIndInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable independent Student Navigation..
        /// </summary>
        internal static string DisableStudentNavigation {
            get {
                return ResourceManager.GetString("DisableStudentNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Student Submissions..
        /// </summary>
        internal static string DisableStudentSubmissions {
            get {
                return ResourceManager.GetString("DisableStudentSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays.
        /// </summary>
        internal static string Displays {
            get {
                return ResourceManager.GetString("Displays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-Monitor.
        /// </summary>
        internal static string DualMonitor {
            get {
                return ResourceManager.GetString("DualMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Slide.
        /// </summary>
        internal static string DuplicateSlide {
            get {
                return ResourceManager.GetString("DuplicateSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable &amp;Logging.
        /// </summary>
        internal static string EnableLogging {
            get {
                return ResourceManager.GetString("EnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable free navigation independent of the instructor.
        /// </summary>
        internal static string EnableNavigationIndInstructor {
            get {
                return ResourceManager.GetString("EnableNavigationIndInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Previews.
        /// </summary>
        internal static string EnablePreviews {
            get {
                return ResourceManager.GetString("EnablePreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable QuickPolling.
        /// </summary>
        internal static string EnableQuickPolling {
            get {
                return ResourceManager.GetString("EnableQuickPolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Dual-Monitor Output.
        /// </summary>
        internal static string EnableSecondMonitor {
            get {
                return ResourceManager.GetString("EnableSecondMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable independent Student Navigation..
        /// </summary>
        internal static string EnableStudentNavigation {
            get {
                return ResourceManager.GetString("EnableStudentNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Student Submissions..
        /// </summary>
        internal static string EnableStudentSubmissions {
            get {
                return ResourceManager.GetString("EnableStudentSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Quick Poll..
        /// </summary>
        internal static string EndQuickPoll {
            get {
                return ResourceManager.GetString("EndQuickPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase all ink from the current slide..
        /// </summary>
        internal static string EraseAllToolTip {
            get {
                return ResourceManager.GetString("EraseAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As &amp;HTML....
        /// </summary>
        internal static string ExportAsHTML {
            get {
                return ResourceManager.GetString("ExportAsHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As &amp;Image....
        /// </summary>
        internal static string ExportAsImage {
            get {
                return ResourceManager.GetString("ExportAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export &amp;Ink....
        /// </summary>
        internal static string ExportInk {
            get {
                return ResourceManager.GetString("ExportInk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend.
        /// </summary>
        internal static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Command:.
        /// </summary>
        internal static string ExtendedCommand {
            get {
                return ResourceManager.GetString("ExtendedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Strip.
        /// </summary>
        internal static string FilmStrip {
            get {
                return ResourceManager.GetString("FilmStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Strip &amp;Alignment.
        /// </summary>
        internal static string FilmStripAlignment {
            get {
                return ResourceManager.GetString("FilmStripAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Strip Width.
        /// </summary>
        internal static string FilmStripWidth {
            get {
                return ResourceManager.GetString("FilmStripWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Linked Navigation.
        /// </summary>
        internal static string ForceLinkedNavigation {
            get {
                return ResourceManager.GetString("ForceLinkedNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information: .
        /// </summary>
        internal static string ForMoreInformation {
            get {
                return ResourceManager.GetString("ForMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward error correction.
        /// </summary>
        internal static string ForwardErrorCorrection {
            get {
                return ResourceManager.GetString("ForwardErrorCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add blank whiteboard slide..
        /// </summary>
        internal static string ForwardTooltipAddBlank {
            get {
                return ResourceManager.GetString("ForwardTooltipAddBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the next slide..
        /// </summary>
        internal static string ForwardTooltipNextSlide {
            get {
                return ResourceManager.GetString("ForwardTooltipNextSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Navigation.
        /// </summary>
        internal static string FullNavigation {
            get {
                return ResourceManager.GetString("FullNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Full Screen.
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green text..
        /// </summary>
        internal static string GreenText {
            get {
                return ResourceManager.GetString("GreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL.
        /// </summary>
        internal static string Highlighter {
            get {
                return ResourceManager.GetString("Highlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image From &amp;Camera.
        /// </summary>
        internal static string InsertImageFromCamera {
            get {
                return ResourceManager.GetString("InsertImageFromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image From Clip&amp;Board.
        /// </summary>
        internal static string InsertImageFromClipboard {
            get {
                return ResourceManager.GetString("InsertImageFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image From &amp;File.
        /// </summary>
        internal static string InsertImageFromFile {
            get {
                return ResourceManager.GetString("InsertImageFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image From Window &amp;Snapshot.
        /// </summary>
        internal static string InsertImageFromSnapshot {
            get {
                return ResourceManager.GetString("InsertImageFromSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert &amp;Slides from Deck....
        /// </summary>
        internal static string InsertSlidesFromDeck {
            get {
                return ResourceManager.GetString("InsertSlidesFromDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor.
        /// </summary>
        internal static string InstructorRole {
            get {
                return ResourceManager.GetString("InstructorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start TCP Server and Take Instructor Role.
        /// </summary>
        internal static string InstructorStartTCPServer {
            get {
                return ResourceManager.GetString("InstructorStartTCPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpacket delay.
        /// </summary>
        internal static string InterpacketDelay {
            get {
                return ResourceManager.GetString("InterpacketDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;IP Address.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer&apos;s IP address is: .
        /// </summary>
        internal static string IPAddressIs {
            get {
                return ResourceManager.GetString("IPAddressIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the Classroom of Instructor:.
        /// </summary>
        internal static string JoinClassroom {
            get {
                return ResourceManager.GetString("JoinClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the Selected
        ///Instructor&apos;s Presentation.
        /// </summary>
        internal static string JoinSelectedPresentation {
            get {
                return ResourceManager.GetString("JoinSelectedPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Getting Started Guide....
        /// </summary>
        internal static string LaunchGettingStartedGuid {
            get {
                return ResourceManager.GetString("LaunchGettingStartedGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light blue text..
        /// </summary>
        internal static string LightblueText {
            get {
                return ResourceManager.GetString("LightblueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light green text..
        /// </summary>
        internal static string LightgreenText {
            get {
                return ResourceManager.GetString("LightgreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File Path:.
        /// </summary>
        internal static string LogFilePath {
            get {
                return ResourceManager.GetString("LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Options.
        /// </summary>
        internal static string LoggingOptions {
            get {
                return ResourceManager.GetString("LoggingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Connection Venues.
        /// </summary>
        internal static string ManualConnectionVenues {
            get {
                return ResourceManager.GetString("ManualConnectionVenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Minimize&quot; the current slide to make room for notes around the outside..
        /// </summary>
        internal static string MinimizeCurrentSlide {
            get {
                return ResourceManager.GetString("MinimizeCurrentSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: For advanced users only. Modify only if you know what you are doing..
        /// </summary>
        internal static string MonitorSetNote {
            get {
                return ResourceManager.GetString("MonitorSetNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information, please visit .
        /// </summary>
        internal static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiCast.
        /// </summary>
        internal static string MultiCast {
            get {
                return ResourceManager.GetString("MultiCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Monitor Switching.
        /// </summary>
        internal static string MultiMonitorSwitching {
            get {
                return ResourceManager.GetString("MultiMonitorSwitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Need restart to take effect.
        /// </summary>
        internal static string NeedRestart {
            get {
                return ResourceManager.GetString("NeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networked.
        /// </summary>
        internal static string NetworkedMode {
            get {
                return ResourceManager.GetString("NetworkedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Slide.
        /// </summary>
        internal static string NewSlide {
            get {
                return ResourceManager.GetString("NewSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Background Template.
        /// </summary>
        internal static string NoBackgroundTemplate {
            get {
                return ResourceManager.GetString("NoBackgroundTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Navigation.
        /// </summary>
        internal static string NoNavigation {
            get {
                return ResourceManager.GetString("NoNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presenter is using a non-standard port number because another application was already using Presenter&apos;s normal port.  If students need to make manual connections, they should specify the port:.
        /// </summary>
        internal static string NonStandardMannulConnect {
            get {
                return ResourceManager.GetString("NonStandardMannulConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Slide.
        /// </summary>
        internal static string NoSlide {
            get {
                return ResourceManager.GetString("NoSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Yet Implemented!.
        /// </summary>
        internal static string NotYetImplemented {
            get {
                return ResourceManager.GetString("NotYetImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Slide.
        /// </summary>
        internal static string OneSlide {
            get {
                return ResourceManager.GetString("OneSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online &amp;Help....
        /// </summary>
        internal static string OnlineHelp {
            get {
                return ResourceManager.GetString("OnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Deck.
        /// </summary>
        internal static string OpenDeck {
            get {
                return ResourceManager.GetString("OpenDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options....
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Set&amp;up....
        /// </summary>
        internal static string PageSetup {
            get {
                return ResourceManager.GetString("PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages Per Sheet.
        /// </summary>
        internal static string PagesPerSheet {
            get {
                return ResourceManager.GetString("PagesPerSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen.
        /// </summary>
        internal static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Color.
        /// </summary>
        internal static string PenColor {
            get {
                return ResourceManager.GetString("PenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Color.
        /// </summary>
        internal static string PenCustomColor {
            get {
                return ResourceManager.GetString("PenCustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        internal static string PenHeight {
            get {
                return ResourceManager.GetString("PenHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        internal static string PenRoundShape {
            get {
                return ResourceManager.GetString("PenRoundShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        internal static string PenShape {
            get {
                return ResourceManager.GetString("PenShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string PenSquareShape {
            get {
                return ResourceManager.GetString("PenSquareShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        internal static string PenTip {
            get {
                return ResourceManager.GetString("PenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Type.
        /// </summary>
        internal static string PenType {
            get {
                return ResourceManager.GetString("PenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        internal static string PenWidth {
            get {
                return ResourceManager.GetString("PenWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to percent.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink text..
        /// </summary>
        internal static string PinkText {
            get {
                return ResourceManager.GetString("PinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Poll....
        /// </summary>
        internal static string Poll {
            get {
                return ResourceManager.GetString("Poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll Type.
        /// </summary>
        internal static string PollType {
            get {
                return ResourceManager.GetString("PollType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentations in Chosen Venue.
        /// </summary>
        internal static string PresentationsInChosenVenue {
            get {
                return ResourceManager.GetString("PresentationsInChosenVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Start Presentation.
        /// </summary>
        internal static string PresenterStartupStepThree {
            get {
                return ResourceManager.GetString("PresenterStartupStepThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Choose a Network Connection.
        /// </summary>
        internal static string PresenterStartupStepTwo {
            get {
                return ResourceManager.GetString("PresenterStartupStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print....
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        internal static string Printing {
            get {
                return ResourceManager.GetString("Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pre&amp;view.
        /// </summary>
        internal static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt on Close.
        /// </summary>
        internal static string PromptOnClose {
            get {
                return ResourceManager.GetString("PromptOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Display.
        /// </summary>
        internal static string PublicDisplayRole {
            get {
                return ResourceManager.GetString("PublicDisplayRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Submissions.
        /// </summary>
        internal static string PublicSubmissions {
            get {
                return ResourceManager.GetString("PublicSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickPoll.
        /// </summary>
        internal static string QuickPoll {
            get {
                return ResourceManager.GetString("QuickPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC.
        /// </summary>
        internal static string QuickPollABC {
            get {
                return ResourceManager.GetString("QuickPollABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD.
        /// </summary>
        internal static string QuickPollABCD {
            get {
                return ResourceManager.GetString("QuickPollABCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDE.
        /// </summary>
        internal static string QuickPollABCDE {
            get {
                return ResourceManager.GetString("QuickPollABCDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        internal static string QuickPollBoth {
            get {
                return ResourceManager.GetString("QuickPollBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string QuickPollC {
            get {
                return ResourceManager.GetString("QuickPollC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string QuickPollD {
            get {
                return ResourceManager.GetString("QuickPollD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote version does not support the QuickPoll feature..
        /// </summary>
        internal static string QuickPollLocalVersionWarning {
            get {
                return ResourceManager.GetString("QuickPollLocalVersionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither.
        /// </summary>
        internal static string QuickPollNeither {
            get {
                return ResourceManager.GetString("QuickPollNeither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string QuickPollNo {
            get {
                return ResourceManager.GetString("QuickPollNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local version does not support the QuickPoll feature..
        /// </summary>
        internal static string QuickPollVersionWarning {
            get {
                return ResourceManager.GetString("QuickPollVersionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string QuickPollYes {
            get {
                return ResourceManager.GetString("QuickPollYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo the most recently undone change..
        /// </summary>
        internal static string RedoTooltipText {
            get {
                return ResourceManager.GetString("RedoTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red text..
        /// </summary>
        internal static string RedText {
            get {
                return ResourceManager.GetString("RedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reenter.
        /// </summary>
        internal static string Reenter {
            get {
                return ResourceManager.GetString("Reenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Node.
        /// </summary>
        internal static string RemoteNode {
            get {
                return ResourceManager.GetString("RemoteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Defaults.
        /// </summary>
        internal static string RestoreDefaults {
            get {
                return ResourceManager.GetString("RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the slide to its original size..
        /// </summary>
        internal static string RestoreSlideSize {
            get {
                return ResourceManager.GetString("RestoreSlideSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTP beacon interval.
        /// </summary>
        internal static string RTPBeaconInterval {
            get {
                return ResourceManager.GetString("RTPBeaconInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTP Connected:.
        /// </summary>
        internal static string RTPConnected {
            get {
                return ResourceManager.GetString("RTPConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All Decks.
        /// </summary>
        internal static string SaveAllDecks {
            get {
                return ResourceManager.GetString("SaveAllDecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All Decks As....
        /// </summary>
        internal static string SaveAllDecksAs {
            get {
                return ResourceManager.GetString("SaveAllDecksAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Deck.
        /// </summary>
        internal static string SaveDeck {
            get {
                return ResourceManager.GetString("SaveDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Deck &amp;As....
        /// </summary>
        internal static string SaveDeckAs {
            get {
                return ResourceManager.GetString("SaveDeckAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Files.
        /// </summary>
        internal static string SavingFiles {
            get {
                return ResourceManager.GetString("SavingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribble Area.
        /// </summary>
        internal static string ScribbleArea {
            get {
                return ResourceManager.GetString("ScribbleArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the black pen..
        /// </summary>
        internal static string SelectBlackPen {
            get {
                return ResourceManager.GetString("SelectBlackPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the blue pen..
        /// </summary>
        internal static string SelectBluePen {
            get {
                return ResourceManager.GetString("SelectBluePen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the custom color highlighter..
        /// </summary>
        internal static string SelectCustomColorHighlighter {
            get {
                return ResourceManager.GetString("SelectCustomColorHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the custom color pen..
        /// </summary>
        internal static string SelectCustomColorPen {
            get {
                return ResourceManager.GetString("SelectCustomColorPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the cyan highlighter..
        /// </summary>
        internal static string SelectCyanHighlighter {
            get {
                return ResourceManager.GetString("SelectCyanHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Eraser..
        /// </summary>
        internal static string SelectEraser {
            get {
                return ResourceManager.GetString("SelectEraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the green highlighter..
        /// </summary>
        internal static string SelectGreenHighlighter {
            get {
                return ResourceManager.GetString("SelectGreenHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the green pen..
        /// </summary>
        internal static string SelectGreenPen {
            get {
                return ResourceManager.GetString("SelectGreenPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Highlighter Stylus..
        /// </summary>
        internal static string SelectHighlighterStylus {
            get {
                return ResourceManager.GetString("SelectHighlighterStylus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the light blue pen..
        /// </summary>
        internal static string SelectLightbluePen {
            get {
                return ResourceManager.GetString("SelectLightbluePen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the light green pen..
        /// </summary>
        internal static string SelectLightgreenPen {
            get {
                return ResourceManager.GetString("SelectLightgreenPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the magenta highlighter..
        /// </summary>
        internal static string SelectMagentaHighlighter {
            get {
                return ResourceManager.GetString("SelectMagentaHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the orange highlighter..
        /// </summary>
        internal static string SelectOrangeHighlighter {
            get {
                return ResourceManager.GetString("SelectOrangeHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Pen Stylus..
        /// </summary>
        internal static string SelectPenStylus {
            get {
                return ResourceManager.GetString("SelectPenStylus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the pink pen..
        /// </summary>
        internal static string SelectPinkPen {
            get {
                return ResourceManager.GetString("SelectPinkPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the red pen..
        /// </summary>
        internal static string SelectRedPen {
            get {
                return ResourceManager.GetString("SelectRedPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the white pen..
        /// </summary>
        internal static string SelectWhitePen {
            get {
                return ResourceManager.GetString("SelectWhitePen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the yellow highlighter..
        /// </summary>
        internal static string SelectYellowHighlighter {
            get {
                return ResourceManager.GetString("SelectYellowHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the yellow pen..
        /// </summary>
        internal static string SelectYellowPen {
            get {
                return ResourceManager.GetString("SelectYellowPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending submission ....
        /// </summary>
        internal static string SendSubmission {
            get {
                return ResourceManager.GetString("SendSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name or address:.
        /// </summary>
        internal static string ServerNameAddress {
            get {
                return ResourceManager.GetString("ServerNameAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Deck Background Template ....
        /// </summary>
        internal static string SetDeckBackgroundTemplate {
            get {
                return ResourceManager.GetString("SetDeckBackgroundTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Deck Background Color ....
        /// </summary>
        internal static string SetDeckBkgColor {
            get {
                return ResourceManager.GetString("SetDeckBkgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Slide Background Template ....
        /// </summary>
        internal static string SetSlideBackgroundTemplate {
            get {
                return ResourceManager.GetString("SetSlideBackgroundTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Slide Background Color ....
        /// </summary>
        internal static string SetSlideBkgColor {
            get {
                return ResourceManager.GetString("SetSlideBkgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS Deck Film Strip Width.
        /// </summary>
        internal static string SSDeckFilmStripWidth {
            get {
                return ResourceManager.GetString("SSDeckFilmStripWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Submission Interval Timer.
        /// </summary>
        internal static string SSTimerPropertiesGroup {
            get {
                return ResourceManager.GetString("SSTimerPropertiesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Start Presentation.
        /// </summary>
        internal static string StandAloneInstrStartupStepTwo {
            get {
                return ResourceManager.GetString("StandAloneInstrStartupStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand Alone.
        /// </summary>
        internal static string StandAloneMode {
            get {
                return ResourceManager.GetString("StandAloneMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a New Presentation.
        /// </summary>
        internal static string StartNewPresentation {
            get {
                return ResourceManager.GetString("StartNewPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Quick Poll..
        /// </summary>
        internal static string StartQuickPoll {
            get {
                return ResourceManager.GetString("StartQuickPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom Presenter 3: Connection Sequence.
        /// </summary>
        internal static string StartupFormText {
            get {
                return ResourceManager.GetString("StartupFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help....
        /// </summary>
        internal static string StartupHelp {
            get {
                return ResourceManager.GetString("StartupHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Choose a Role.
        /// </summary>
        internal static string StartupStepOne {
            get {
                return ResourceManager.GetString("StartupStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Client.
        /// </summary>
        internal static string StudentClient {
            get {
                return ResourceManager.GetString("StudentClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentNavigationType.
        /// </summary>
        internal static string StudentNavigationType {
            get {
                return ResourceManager.GetString("StudentNavigationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string StudentRole {
            get {
                return ResourceManager.GetString("StudentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Submissions.
        /// </summary>
        internal static string StudentSubmissions {
            get {
                return ResourceManager.GetString("StudentSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Submission Timer.
        /// </summary>
        internal static string StudentSubmissionTimerProperties {
            get {
                return ResourceManager.GetString("StudentSubmissionTimerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission failed!.
        /// </summary>
        internal static string SubmissionFailed {
            get {
                return ResourceManager.GetString("SubmissionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Interval(s).
        /// </summary>
        internal static string SubmissionIntervalLabel {
            get {
                return ResourceManager.GetString("SubmissionIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission received!.
        /// </summary>
        internal static string SubmissionReceived {
            get {
                return ResourceManager.GetString("SubmissionReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to the last non-Whiteboard Deck..
        /// </summary>
        internal static string SwitchToNonWhiteboardDeck {
            get {
                return ResourceManager.GetString("SwitchToNonWhiteboardDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to the Whiteboard Deck..
        /// </summary>
        internal static string SwitchWhiteboardDeck {
            get {
                return ResourceManager.GetString("SwitchWhiteboardDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP Client Attempting to Connect.
        /// </summary>
        internal static string TCPClientAttemptingConnect {
            get {
                return ResourceManager.GetString("TCPClientAttemptingConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP Client Connected.
        /// </summary>
        internal static string TCPClientConnected {
            get {
                return ResourceManager.GetString("TCPClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP Server Connected.
        /// </summary>
        internal static string TCPServerConnected {
            get {
                return ResourceManager.GetString("TCPServerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Classroom Presenter Version: .
        /// </summary>
        internal static string ThisClassroomPresenterVersion {
            get {
                return ResourceManager.GetString("ThisClassroomPresenterVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Slides.
        /// </summary>
        internal static string ThreeSlides {
            get {
                return ResourceManager.GetString("ThreeSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor.
        /// </summary>
        internal static string TitleRoleInstructor {
            get {
                return ResourceManager.GetString("TitleRoleInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string TitleRolePublic {
            get {
                return ResourceManager.GetString("TitleRolePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string TitleRoleStudent {
            get {
                return ResourceManager.GetString("TitleRoleStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        internal static string Toolbar {
            get {
                return ResourceManager.GetString("Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your decks?.
        /// </summary>
        internal static string ToSaveDeck {
            get {
                return ResourceManager.GetString("ToSaveDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Slides.
        /// </summary>
        internal static string TwoSlides {
            get {
                return ResourceManager.GetString("TwoSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Changes.
        /// </summary>
        internal static string UndoChanges {
            get {
                return ResourceManager.GetString("UndoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo the most recent change..
        /// </summary>
        internal static string UndoTooltipText {
            get {
                return ResourceManager.GetString("UndoTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicast.
        /// </summary>
        internal static string Unicast {
            get {
                return ResourceManager.GetString("Unicast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Connection Status..
        /// </summary>
        internal static string UnknownConnectionStatus {
            get {
                return ResourceManager.GetString("UnknownConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Name.
        /// </summary>
        internal static string UnknownName {
            get {
                return ResourceManager.GetString("UnknownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Version.
        /// </summary>
        internal static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Untitled Presentation).
        /// </summary>
        internal static string UntitledPresentation {
            get {
                return ResourceManager.GetString("UntitledPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvisited Slide.
        /// </summary>
        internal static string UnvisitedSlide {
            get {
                return ResourceManager.GetString("UnvisitedSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Custom Commands.
        /// </summary>
        internal static string UseCustomCommands {
            get {
                return ResourceManager.GetString("UseCustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Light Color Set.
        /// </summary>
        internal static string UseLightColorSet {
            get {
                return ResourceManager.GetString("UseLightColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Window APIs.
        /// </summary>
        internal static string UseWindowAPIs {
            get {
                return ResourceManager.GetString("UseWindowAPIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presenter is Using a Non-Standard Port.
        /// </summary>
        internal static string UsingNonStandardPort {
            get {
                return ResourceManager.GetString("UsingNonStandardPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Compatibility Information.
        /// </summary>
        internal static string VersionCompatibilityInformation {
            get {
                return ResourceManager.GetString("VersionCompatibilityInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node has not responded to a version request.  It is probably a pre-release version..
        /// </summary>
        internal static string VersionCompatibilityNoResponse {
            get {
                return ResourceManager.GetString("VersionCompatibilityNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Version Compatibility Info ....
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Join Presentation.
        /// </summary>
        internal static string ViewerStartupStepThree {
            get {
                return ResourceManager.GetString("ViewerStartupStepThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Choose a Presentation.
        /// </summary>
        internal static string ViewerStartupStepTwo {
            get {
                return ResourceManager.GetString("ViewerStartupStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited Slides Navigation.
        /// </summary>
        internal static string VisitedSlidesNavigation {
            get {
                return ResourceManager.GetString("VisitedSlidesNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhiteBoard.
        /// </summary>
        internal static string WhiteBoard {
            get {
                return ResourceManager.GetString("WhiteBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Text..
        /// </summary>
        internal static string WhiteText {
            get {
                return ResourceManager.GetString("WhiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of Preview.
        /// </summary>
        internal static string WidthOfPreview {
            get {
                return ResourceManager.GetString("WidthOfPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow text..
        /// </summary>
        internal static string YellowText {
            get {
                return ResourceManager.GetString("YellowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zoom Slide.
        /// </summary>
        internal static string ZoomSlide {
            get {
                return ResourceManager.GetString("ZoomSlide", resourceCulture);
            }
        }
    }
}
